export const AppName = "Prepare Safe";
export const AppDescription = "Adds your existing EOA as an owner to a Circles Safe.";
export const AppIcon = "'<svg></svg>'";
export const RpcEndpoint = "https://rpc.circlesubi.id/";
export const CirclesGardenApi = `https://api.circles.garden/`;
export const CirclesSubgraphApi = `https://api.thegraph.com/subgraphs/name/circlesubi/circles-ubi`;
export const HubAddress = "0x29b9a7fBb8995b2423a71cC17cf9810798F6C543";
export const CirclesUbiIdApi = "https://dev.api.circlesubi.id/";
export const HoGTokenAddress = "0x6de572faa138048ce8142c4a206eb09a8ec39e45"
